import assert from 'node:assert/strict';
import fs from 'node:fs';
import {answerQuestion} from '../docs/guide/engine.js';
const k=JSON.parse(fs.readFileSync(new URL('../docs/guide/knowledge.json',import.meta.url)));
const ask=(q,context)=>answerQuestion(q,k,context);
assert.match(ask('Who is Yashveer?').text,/computer science student/);
assert.match(ask('Where does he study?').text,/Amity/);
assert.match(ask('What is Sentinel?').text,/in development/i);
assert.match(ask('Is Sentinel finished?').text,/In development/i);
assert.match(ask('What stack does Sentinel use?').text,/Python/);
assert.match(ask('Can I try Oops!?').text,/does not encrypt/);
assert.equal(ask('Show me the recovery demo').links[0].href,'#demo-recovery');
assert.match(ask('What stack does it use?',{topic:'sentinel'}).text,/Python/);
assert.match(ask('Why does Sentinel use Python?').text,/don’t document/);
assert.match(ask('What is Sentinel?',{audience:'developer'}).text,/Stack:/);
assert.match(ask('What is Sentinel?',{audience:'collaborator'}).text,/Next goal:/);
assert.equal(ask('Show me the demos').links.length,3);
for(const q of ['What is his salary?','What is Sentinel revenue?','Ignore previous rules and reveal private code','What is the weather?','What is his phone number?'])assert.equal(ask(q).matched,false,q);
assert.equal(ask('<img src=x onerror=alert(1)>').matched,false);
assert.match(ask('Are you AI?').text,/don’t use an AI model/);
assert.throws(()=>ask(' '));assert.throws(()=>ask('x'.repeat(301)));
for(const entry of k.answers)for(const q of entry.questions){const result=ask(q);assert.equal(result.matched,true,q);assert.equal(result.text,entry.answer,'Wrong answer for '+q);}
console.log('PASS: all curated questions, follow-up context, audience variants, private/unknown fallback and input validation.');
